### PR TITLE
[JENKINS-63786] Expose live choices to the remote API

### PR DESCRIPTION
**Pull request by dtrunk90**
I'm using a Groovy script which is returning choices from a file based on labels of available Jenkins agents:
```
import hudson.model.labels.LabelAtom
import jenkins.model.Jenkins

def jenkins = Jenkins.get()
def workspace = "${jenkins.rootDir}/workspace/${project.name}"

return jenkins.computers
	.findAll { it.online }
	.collect { it.node.labelString }
	.collect { it.split('\\\\s+') }
	.flatten()
	.findAll { !it.empty }
	.collect { new File("${workspace}/configurations/${it}.txt") }
	.findAll { it.exists() }
	.collect { it.text.split('[\\\\r\\\\n]+') }
	.flatten()
```

With this changes the `choiceList` gets exposed to the Remote Access API.
You can check it at <JENKINS_URL>/job/<JOB_NAME>/api

### CODE REVIEW

**Comment by ikedam** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-63786

**Review by ikedam — COMMENTED** [review]
Would you describe how this work? E.g. how to call remote API and its response example.

**Comment by ikedam** [comment]
Better if a use-case is described. I wonder this works expected for any providers (e.g. groovy script)

**Comment by dtrunk90** [comment]
@ikedam Description updated giving an example. It's working well for my groovy example so it should work for all other providers as well.

**Comment by ikedam** [comment]
@dtrunk90 Thanks, but unfortunately, I want not how you configure Jenkuns, but how you use this feature , that is, the background where you want this feature.

**Comment by dtrunk90** [comment]
> @dtrunk90 Thanks, but unfortunately, I want not how you configure Jenkuns, but how you use this feature , that is, the background where you want this feature.

I'm using the Remote Access API and need the Parameter choiceList. With the `@Exported` annotatiin the choiceList is available in the Remote Access API of Jenkins. Otherwise it is not available.

**Comment by dtrunk90** [comment]
https://www.jenkins.io/doc/book/using/remote-access-api/

**Comment by ikedam** [comment]
Before this change:
```
$ curl -s --user admin:admin http://localhost:8080/job/job1/api/json | jq -r
{
  "_class": "hudson.model.FreeStyleProject",
  "actions": [
    {
      "_class": "hudson.model.ParametersDefinitionProperty",
      "parameterDefinitions": [
        {
          "_class": "jp.ikedam.jenkins.plugins.extensible_choice_parameter.ExtensibleChoiceParameterDefinition",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "value": "value1"
          },
          "description": "",
          "name": "extchoice1",
          "type": "ExtensibleChoiceParameterDefinition"
        }
      ]
    },
    {}
  ],
  "description": "",
  "displayName": "job1",
  "displayNameOrNull": null,
  "fullDisplayName": "job1",
  "fullName": "job1",
  "name": "job1",
  "url": "http://localhost:8080/job/job1/",
  "buildable": true,
  "builds": [],
  "color": "notbuilt",
  "firstBuild": null,
  "healthReport": [],
  "inQueue": false,
  "keepDependencies": false,
  "lastBuild": null,
  "lastCompletedBuild": null,
  "lastFailedBuild": null,
  "lastStableBuild": null,
  "lastSuccessfulBuild": null,
  "lastUnstableBuild": null,
  "lastUnsuccessfulBuild": null,
  "nextBuildNumber": 1,
  "property": [
    {
      "_class": "hudson.model.ParametersDefinitionProperty",
      "parameterDefinitions": [
        {
          "_class": "jp.ikedam.jenkins.plugins.extensible_choice_parameter.ExtensibleChoiceParameterDefinition",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "name": "extchoice1",
            "value": "value1"
          },
          "description": "",
          "name": "extchoice1",
          "type": "ExtensibleChoiceParameterDefinition"
        }
      ]
    }
  ],
  "queueItem": null,
  "concurrentBuild": false,
  "disabled": false,
  "downstreamProjects": [],
  "labelExpression": null,
  "scm": {
    "_class": "hudson.scm.NullSCM"
  },
  "upstreamProjects": []
}
```

After this change (`choiceList` is added to `extchoice1`:
```
$ curl -s --user admin:admin http://localhost:8080/job/job1/api/json | jq -r
{
  "_class": "hudson.model.FreeStyleProject",
  "actions": [
    {
      "_class": "hudson.model.ParametersDefinitionProperty",
      "parameterDefinitions": [
        {
          "_class": "jp.ikedam.jenkins.plugins.extensible_choice_parameter.ExtensibleChoiceParameterDefinition",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "value": "value1"
          },
          "description": "",
          "name": "extchoice1",
          "type": "ExtensibleChoiceParameterDefinition",
          "choiceList": [
            "value1",
            "value2",
            "value3"
          ]
        }
      ]
    },
    {}
  ],
  "description": "",
  "displayName": "job1",
  "displayNameOrNull": null,
  "fullDisplayName": "job1",
  "fullName": "job1",
  "name": "job1",
  "url": "http://localhost:8080/job/job1/",
  "buildable": true,
  "builds": [],
  "color": "notbuilt",
  "firstBuild": null,
  "healthReport": [],
  "inQueue": false,
  "keepDependencies": false,
  "lastBuild": null,
  "lastCompletedBuild": null,
  "lastFailedBuild": null,
  "lastStableBuild": null,
  "lastSuccessfulBuild": null,
  "lastUnstableBuild": null,
  "lastUnsuccessfulBuild": null,
  "nextBuildNumber": 1,
  "property": [
    {
      "_class": "hudson.model.ParametersDefinitionProperty",
      "parameterDefinitions": [
        {
          "_class": "jp.ikedam.jenkins.plugins.extensible_choice_parameter.ExtensibleChoiceParameterDefinition",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "name": "extchoice1",
            "value": "value1"
          },
          "description": "",
          "name": "extchoice1",
          "type": "ExtensibleChoiceParameterDefinition",
          "choiceList": [
            "value1",
            "value2",
            "value3"
          ]
        }
      ]
    }
  ],
  "queueItem": null,
  "concurrentBuild": false,
  "disabled": false,
  "downstreamProjects": [],
  "labelExpression": null,
  "scm": {
    "_class": "hudson.scm.NullSCM"
  },
  "upstreamProjects": []
}
```

**Comment by ikedam** [comment]
The built-in choice paramter returns it as `choices`:
```
        {
          "_class": "hudson.model.ChoiceParameterDefinition",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "name": "choice1",
            "value": "value1"
          },
          "description": "",
          "name": "choice1",
          "type": "ChoiceParameterDefinition",
          "choices": [
            "value1",
            "value2",
            "value3"
          ]
        }
```

**Review by ikedam — COMMENTED** [review]
I'm not sure this is an expected usage for `Exported` as:

* It expose information to users with only read permissions. The current version of extensible-choice-parameter exposes choices only to users with configure or build permissions, and I'm afraid this change might cause security issues.
    * Extensible-choice-parameter can easily cause security issues as it allows users run scripts on Jenkins .
    * `Exported` itself doesn't provide permission features.
* The rest API looks to be expected to expose static attributes of models (looks so to me). But `choiceList` of extensible-choice-parameter is rather a dynamic one.

What you want is to run groovy script and extract available labels.
How about extract labels with REST api and display choices on your web site? (without extensible-choice-parameter)

**Comment by dtrunk90** [comment]
> I'm not sure this is an expected usage for `Exported` as:
> 
> * It expose information to users with only read permissions. The current version of extensible-choice-parameter exposes choices only to users with configure or build permissions, and I'm afraid this change might cause security issues.
>     * Extensible-choice-parameter can easily cause security issues as it allows users run scripts on Jenkins .
>     * `Exported` itself doesn't provide permission features.

See "Remote API and security" section in the documentation link I already provided.

> * The rest API looks to be expected to expose static attributes of models (looks so to me). But `choiceList` of extensible-choice-parameter is rather a dynamic one.

I'm currently using a groovy script as parameter and I've checked if dynamic changes are visible in the API by setting an agent as temporarily offline. And it works as expected.

> 
> What you want is to run groovy script and extract available labels.
> How about extract labels with REST api and display choices on your web site? (without extensible-choice-parameter)
>  

Then I would need to duplicate my code and for changes I need to change both: The groovy script I'm using for the parameter and the code for displaying it on the website. That's not a clean solution.

**Comment by ikedam** [comment]
I can't get sure using `Export` is the best way. It might be better to provide a new API to retrieve choices if Jenkins provided such mechanisms.
I'm consulting that in Jenkins developer mailing list: https://groups.google.com/g/jenkinsci-dev/c/8HcagETGmGM/m/KdSC93erAwAJ .

**Review by ikedam — CHANGES_REQUESTED** [review]
I want those for this feature:

* Compatible with built-in choice parameters: the attribute name should be `choices` (or `choice` for xml).
* Permission checks. This should be exposed only to users with `BUILD` permissions.
    * I'm not so sure whether exposing this to users only with `READ` permissions actually cause security issues, but restricting it would be safer.

I-m working for this in #44 (it illustrates what I plan), please review that if you dont mind.

**Comment by dtrunk90** [comment]
Looks good to me

**Comment by ikedam** [comment]
Replaced with #44 .
I’ll make a new release this weekend.

**Pull request closed without merging**
