### PR TITLE
Exclude helptext with information about how to specify multiple patterns

### PR DESCRIPTION
**Pull request by phoenix384**
Exclude helptext is missing information about how to specify multiple patterns

### CODE REVIEW

**Comment by ikedam** [comment]
Those messages are completely same to those of the help of "File Name Pattern" field.
I don't want to duplicate messages.
"See the help of File name pattern for the formats of patterns" is more reasonable, isn't it?

**Comment by phoenix384** [comment]
If you think so. As a user I would probably prefer not to be delegated to another helptext to get my information. But anyway, there should be some kind of hint.
I needed to specify multiple patterns in the exclude field and that helptext wasn't helpful. I didn't know whether they have to be comma-separated or whitespace separated or if they even have to be a regular expression. I ended up looking in the code (instead of just looking in the other field's helptext - now I know that ;) ).
That's why this pull request.

**Comment by ikedam** [comment]
Created #19 instead.

**Comment by ikedam** [comment]
merged #19 instead.

**Pull request closed without merging**
